// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuP8ZNuOBG7n8XqoibampbM0hqHzr1Mfw',
    appId: '1:1078195705464:web:d88e4860d49897d96a3f8d',
    messagingSenderId: '1078195705464',
    projectId: 'flutter-firebase-tts11',
    authDomain: 'flutter-firebase-tts11.firebaseapp.com',
    storageBucket: 'flutter-firebase-tts11.firebasestorage.app',
    measurementId: 'G-MXMTLZX76D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhOqZE4iDkX9aHvLcRPuIe9fTE-CEx1A',
    appId: '1:1078195705464:android:a5290023e6f3796d6a3f8d',
    messagingSenderId: '1078195705464',
    projectId: 'flutter-firebase-tts11',
    storageBucket: 'flutter-firebase-tts11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZ7-ik29FY8o431niRBQ3oneSVX9Tqts',
    appId: '1:1078195705464:ios:e2af16cfbf27fd916a3f8d',
    messagingSenderId: '1078195705464',
    projectId: 'flutter-firebase-tts11',
    storageBucket: 'flutter-firebase-tts11.firebasestorage.app',
    iosBundleId: 'com.example.flFirebase',
  );
}
